# -*- coding: utf-8 -*-
"""PlantDiseaseDetection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13-9MRuRTSCj9AF40qNXEQABbxjUHCy-M
"""

# ============================================================
# STEP 1 — INSTALL + IMPORT + DOWNLOAD PLANT VILLAGE DATASET
# ============================================================

!pip install -q kagglehub tensorflow==2.19.0

import kagglehub
import os
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models, optimizers, callbacks
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input as resnet_preprocess

print("TensorFlow version:", tf.__version__)

# Download dataset
dataset_path = kagglehub.dataset_download("adilmubashirchaudhry/plant-village-dataset")
print("Dataset downloaded to:", dataset_path)

# ============================================================
# STEP 2 — CREATE CSV FROM IMAGE FOLDERS
# ============================================================

image_data = []
for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.lower().endswith((".jpg", ".jpeg", ".png")):
            filepath = os.path.join(root, file)
            label = os.path.basename(root)
            image_data.append([filepath, label])

df = pd.DataFrame(image_data, columns=["filepath", "label"])
df.to_csv("/content/plant_village_dataset.csv", index=False)

print("CSV created with", len(df), "images.")
df.head()

# ============================================================
# STEP 3 — REDUCE DATA + SPLIT
# ============================================================

trainval_df, test_df = train_test_split(df, test_size=0.10, stratify=df["label"], random_state=42)
train_df, val_df = train_test_split(trainval_df, test_size=0.15, stratify=trainval_df["label"], random_state=42)

# Reduce dataset for speed
train_df = train_df.sample(frac=0.20, random_state=42)
val_df   = val_df.sample(frac=0.20, random_state=42)

num_classes = df["label"].nunique()

print("Train:", len(train_df), "Val:", len(val_df), "Test:", len(test_df))
print("Classes:", num_classes)

# ============================================================
# STEP 4 — GENERATORS
# ============================================================

IMG_SIZE = (128, 128)
BATCH_SIZE = 64

def make_gens(pre_fn):
    train_datagen = ImageDataGenerator(
        preprocessing_function=pre_fn,
        rotation_range=20,
        zoom_range=0.2,
        width_shift_range=0.1,
        height_shift_range=0.1,
        horizontal_flip=True
    )

    val_datagen = ImageDataGenerator(preprocessing_function=pre_fn)

    train_gen = train_datagen.flow_from_dataframe(
        train_df, x_col="filepath", y_col="label",
        target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode="categorical"
    )

    val_gen = val_datagen.flow_from_dataframe(
        val_df, x_col="filepath", y_col="label",
        target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode="categorical"
    )

    test_gen = val_datagen.flow_from_dataframe(
        test_df, x_col="filepath", y_col="label",
        target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode="categorical", shuffle=False
    )

    return train_gen, val_gen, test_gen

train_gen, val_gen, test_gen = make_gens(resnet_preprocess)

# ============================================================
# STEP 5 — RESNET50 TRANSFER LEARNING MODEL
# ============================================================

def build_resnet50_model(num_classes):
    base = ResNet50(weights="imagenet", include_top=False,
                    pooling="avg", input_shape=IMG_SIZE + (3,))

    base.trainable = False  # feature extractor

    inp = layers.Input(shape=IMG_SIZE + (3,))
    x = layers.Lambda(resnet_preprocess)(inp)
    x = base(x, training=False)
    x = layers.Dense(256, activation="relu")(x)
    x = layers.Dropout(0.4)(x)
    out = layers.Dense(num_classes, activation="softmax")(x)

    model = models.Model(inp, out)
    return model, base

model, base_model = build_resnet50_model(num_classes)
model.summary()

# ============================================================
# STEP 6 — SUPER FAST TRAINING (RESNET50)
# ============================================================

BASE_EPOCHS = 1
FINE_TUNE_EPOCHS = 1
FINE_TUNE_AT = 100   # Unfreeze deeper layers

# -------- Step 1: Train classifier head --------
model.compile(
    optimizer=optimizers.Adam(1e-3),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

print("🔹 Training classifier head...")
model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=BASE_EPOCHS
)

# -------- Step 2: Fine-Tuning --------
print("🔹 Fine-tuning ResNet50...")

base_model.trainable = True

# freeze first 100 layers
for layer in base_model.layers[:FINE_TUNE_AT]:
    layer.trainable = False

model.compile(
    optimizer=optimizers.Adam(1e-5),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=FINE_TUNE_EPOCHS
)

# ============================================================
# STEP 7 — TEST + EXPORT
# ============================================================

loss, acc = model.evaluate(test_gen)
print(f"TEST ACCURACY: {acc*100:.2f}%")

model.save("/content/resnet50_plantvillage.h5")
from google.colab import files
files.download("/content/resnet50_plantvillage.h5")